# Generated by Django 4.0.6 on 2022-07-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kichen', 'kitchen'), ('client', 'client')], max_length=30, verbose_name='тип чека которые печатает принтер')),
                ('order', models.JSONField(verbose_name='информация о заказе')),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], max_length=20, verbose_name='статус чека')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='ссылка на созданный PDF-файл')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printers.printer', verbose_name='принтер')),
            ],
        ),
    ]
