# Generated by Django 4.0.6 on 2022-07-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
    ]
