# Generated by Django 4.0.6 on 2022-07-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_alter_check_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=30, verbose_name='тип чека которые печатает принтер'),
        ),
    ]
