# Generated by Django 4.0.6 on 2022-07-07 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название принтера')),
                ('api_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ключ доступа к API')),
                ('check_type', models.CharField(choices=[('kichen', 'kitchen'), ('client', 'client')], max_length=20, verbose_name='тип чека которые печатает принтер')),
                ('point_id', models.IntegerField(verbose_name='точка к которой привязан принтер')),
            ],
        ),
    ]
