# Generated by Django 4.0.6 on 2022-07-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Принтер', 'verbose_name_plural': 'Принтеры'},
        ),
        migrations.AlterUniqueTogether(
            name='printer',
            unique_together={('point_id', 'check_type')},
        ),
    ]
